apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: server
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: prometheus
      component: server
      release: {{ .Release.Name }}
