version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - sgibson91
      - callummole
      - lukehare
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    reviewers:
      - sgibson91
      - callummole
      - lukehare
