trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python 37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: brew upgrade
    displayName: 'Updating Homebrew'

  - script: brew install azure-cli
    displayName: 'Brew installing Azure CLI'

  - script: brew install kubernetes-cli
    displayName: 'Brew installing kubectl'

  - script: brew install kubernetes-helm
    displayName: 'Brew installing helm'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Installing dependencies'

  - script: python generate-configs.py --sp-login --sp-app-id $(SP-appID) --sp-key $(SP-key)
    displayName: 'Generate config files for Hub23'

  - script: python upgrade.py --sp-login --sp-app-id $(SP-appID) --sp-key $(SP-key)
    displayName: 'Upgrading Hub23 helm chart'
