trigger:
  - master

jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      - task: AzureCLI@1
        inputs:
          scriptLocation: 'inlineScript'
          inlineScript: ''
          addSpnToEnvironment: true
          connectedServiceNameARM: hub23-deploy-scn
