trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python 37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Installing Azure CLI'

  - script: |
      sudo apt-get update && sudo apt-get install -y apt-transport-https
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubectl
    displayName: 'Installing kubectl'

  - script: |
      curl -LO https://git.io/get_helm.sh
      chmod 700 get_helm.sh
      ./get_helm.sh
    displayName: 'Installing helm'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Installing dependencies'

  - script: python generate-configs.py --sp-login --sp-app-id $(appId) --sp-key $(appKey)
    displayName: 'Generate config files for Hub23'

  - script: python upgrade.py --sp-login --sp-app-id $(appId) --sp-key $(appKey)
    displayName: 'Upgrading Hub23 helm chart'
