binderhub:
  registry:
    username: <username>
    password: <password>

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "<apiToken>"
    proxy:
      secretToken: "<secretToken>"
