binderhub:
  registry:
    url: https://<acr-name>.azurecr.io
    username: <username>
    password: <password>

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "<apiToken>"
    proxy:
      secretToken: "<secretToken>"
