projectName: hub23

binderhub:
  config:
    BinderHub:
      auth_enabled: true
      use_named_servers: true

  jupyterhub:
    cull:
      # don't cull authenticated users
      users: False
    custom:
      binderauth_enabled: true
    hub:
      allowNamedServers: true
      namedServerLimitPerUser: 2
      redirectToServer: false
      services:
        binder:
          oauth_redirect_uri: "http://51.145.189.150/oauth_callback"
          oauth_client_id: "binder-oauth-client-test"

    singleuser:
      # to make notebook servers aware of hub
      cmd: jupyterhub-singleuser

    auth:
      type: github
      github:
        callbackUrl: "http://51.105.168.213/hub/oauth_callback"
      scopes:
        - "read:user"
      admin:
        users:
          - 'sgibson91'
