projectName: hub23

binderhub:
  config:
    BinderHub:
      image_prefix: "hub23registry.azurecr.io/hub23/binder-dev-"
      hub_url: "https://hub.hub23.turing.ac.uk"
      use_named_servers: true

    DockerRegistry:
      token_url: "https://hub23registry.azurecr.io/oauth2/token?service=hub23registry.azurecr.io"

  registry:
    url: "https://hub23registry.azurecr.io"

  jupyterhub:
    cull:
      every: 660
      timeout: 600
      # maxAge is 6 hours: 6 * 3600 = 21600
      maxAge: 21600

    custom:
      binderauth_enabled: true

    hub:
      allowNamedServers: true
      redirectToServer: false
      namedServerLimitPerUser: 5

      services:
        binder:
          oauth_redirect_uri: "https://binder.hub23.turing.ac.uk/oauth_callback"
          oauth_client_id: "binder-oauth-client-test"

    singleuser:
      cmd: "jupyterhub-singleuser"
      memory:
        limit: 1G
        guarantee: 1G
      cpu:
        limit: .5
        guarantee: .5

    prePuller:
      continuous:
        enabled: true

    scheduling:
      podPriority:
        enabled: true
      userPlaceholder:
        replicas: 3
      userScheduler:
        enabled: true
      corePods:
        nodeAffinity:
          matchNodePurpose: require
      userPods:
        nodeAffinity:
          matchNodePurpose: prefer

    auth:
      type: github
      github:
        callbackUrl: "https://hub.hub23.turing.ac.uk/hub/oauth_callback"
        orgWhitelist:
          - "binderhub-test-org"
      scopes:
        - "read:user"
