projectName: hub23

binderhub:
  config:
    BinderHub:
      image_prefix: hub23registry.azurecr.io/hub23/binder-dev-
      hub_url: https://hub.hub23.turing.ac.uk
    DockerRegistry:
      token_url: "https://hub23registry.azurecr.io/oauth2/token?service=hub23registry.azurecr.io"

  ingress:
    hosts:
      - binder.hub23.turing.ac.uk

  jupyterhub:
    ingress:
      hosts:
        - hub.hub23.turing.ac.uk
      tls:
        - secretName: kubelego-tls-jupyterhub-hub23
          hosts:
            - hub.hub23.turing.ac.uk

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 52.174.199.172
