binderhub:
  config:
    GitHubRepoProvider:
      access_token: {binderhub_access_token}

  registry:
    username: {username}
    password: {password}

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "{apiToken}"
    proxy:
      secretToken: "{secretToken}"
