binderhub:
  config:
    GitHubRepoProvider:
      access_token: "{binderhub_access_token}"

  registry:
    username: "{username}"
    password: "{password}"

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "{apiToken}"

      config:
        Authenticator:
          admin_users:
            - "sgibson91"
        GitHubOAuthenticator:
          client_id: "{github_client_id}"
          client_secret: "{github_client_secret}"
        JupyterHub:
          admin_access: true

    proxy:
      secretToken: "{secretToken}"
