projectName: hub23

binderhub:
  config:
    BinderHub:
      image_prefix: hub23registry.azurecr.io/hub23/binder-dev-

    DockerRegistry:
      token_url: "https://hub23registry.azurecr.io/oauth2/token?service=hub23registry.azurecr.io"

  registry:
    url: https://hub23registry.azurecr.io

  jupyterhub:
    cull:
      every: 660
      timeout: 600
      maxAge: 21600  # maxAge is 6 hours: 6 * 3600 = 21600

    singleuser:
      memory:
        limit: 1G
        guarantee: 1G
      cpu:
        limit: .5
        guarantee: .5

    prePuller:
      continuous:
        enabled: true

    scheduling:
      podPriority:
        enabled: true
      userPlaceholder:
        replicas: 3
      userScheduler:
        enabled: true
      corePods:
        nodeAffinity:
          matchNodePurpose: require
      userPods:
        nodeAffinity:
          matchNodePurpose: prefer
