binderhub:
  registry:
    username: {username}
    password: {password}

  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "{apiToken}"
    proxy:
      secretToken: "{secretToken}"

  config:
    GitHubRepoProvider:
      access_token: "{binderhub_access_token}"

    auth:
      github:
        clientId: "{github_client_id}"
        clientSecret: "{github_client_secret}"
