projectName: hub23

binderhub:
  config:
    BinderHub:
      hub_url: https://hub.hub23.turing.ac.uk
      image_prefix: hub23registry.azurecr.io/binder-prod-

  ingress:
    hosts:
      - binder.hub23.turing.ac.uk

  jupyterhub:
    proxy:
      nodeSelector:
    ingress:
      hosts:
        - hub.hub23.turing.ac.uk
      tls:
        - secretName: kubelego-tls-jupyterhub-hub
          hosts:
            - hub.hub23.turing.ac.uk


nginx-ingress:
  controller:
    service:
      loadBalancerIP: <unknown>
