dependencies:
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 7.4.4
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 1.18.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: binderhub
   version: 0.2.0-5ca42ec
   repository: https://jupyterhub.github.io/helm-chart
