dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-n555.heb692c5
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 3.29.0
