dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-5b3824d
- name: nginx-ingress
  version: "1.24.3"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: cert-manager
  version: "v0.10.0"
  repository: "https://charts.jetstack.io"
