dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-n388.h9cc5a54
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.41.3
