dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.2.0-n839.hf8a9d7a
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 2.13.0
