dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.1.0-456.7e32ac0
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.25.0
- name: cert-manager
  repository: https://charts.jetstack.io
  version: v0.10.0
