rbac:
  enabled: true

letsencrypt:
  contactEmail: hub23registry@turing.ac.uk

binderhub:
  config:
    BinderHub:
      use_registry: true
      auth_enabled: true

      template_path: /etc/binderhub/custom/templates
      extra_static_path: /etc/binderhub/custom/static
      extra_static_url_prefix: /extra_static/
      template_variables:
        EXTRA_STATIC_URL_PREFIX: "/extra_static/"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      # cert-manager provides a TLS secret
      # This will ask cert-manager to be configured with default values. It's better to configure default values.
      kubernetes.io/tls-acme: "true"
      # nginx-ingress controller to be explicitly utilised instead of "gce"
      # This is required to allow nginx-ingress-controller to function. This will override any cloud provided ingress controllers and use the one we choose to deploy, i.e. nginx.
      kubernetes.io/ingress.class: nginx
    hosts:
      - binder.hub23.turing.ac.uk
    tls:
      - secretName: hub23-binder-tls
        hosts:
          - binder.hub23.turing.ac.uk

  jupyterhub:
    hub:
      extraConfig:
        myConfig:  |
          c.KubeSpawner.pod_name_template = 'jupyter-{username}{servername}'

    auth:
      admin:
        access: true
        users:
          - "sgibson91"

    proxy:
      service:
        type: ClusterIP

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
      hosts:
        - hub.hub23.turing.ac.uk
      tls:
        - secretName: hub23-hub-tls
          hosts:
            - hub.hub23.turing.ac.uk

  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/alan-turing-institute/hub23-deploy
        - /etc/binderhub/custom
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/custom
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/custom

nginx-ingress:
  controller:
    config:
      proxy-body-size: 64m

cert-manager:
  ingressShim:
    defaultIssuerName: "staging"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
