letsencrypt:
  contactEmail: hub23registry@turing.ac.uk

binderhub:
  pdb:
    minAvailable: 0
  replicas: 1
  resources:
    requests:
      cpu: "0.25"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  config:
    BinderHub:
      debug: true
      hub_url: http://51.105.168.213
      per_repo_quota: 100
      per_repo_quota_higher: 200
      use_registry: true
      image_prefix: hub23registry.azurecr.io/testhub/binder-dev-

    DockerRegistry:
      token_url: https://hub23registry.azurecr.io/oauth2/token?service=hub23registry.azurecr.io

  imageCleaner:
    enabled: false

  jupyterhub:
    debug:
      enabled: true

    hub:
      pdb:
        minAvailable: 0
      redirectToServer: false
      shutdownOnLogout: true
      extraConfig:
        01-hub: |
          if "cookie_options" in c.JupyterHub.tornado_settings:
            c.JupyterHub.tornado_settings["cookie_options"].update({"secure": True})
          else:
            c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)
        02-never-restart: |
          c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})
      resources:
        requests:
          cpu: "0.25"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi

    proxy:
      pdb:
        minAvailable: 0
      chp:
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi

    singleuser:
      cpu:
        guarantee: 0.1
        limit: 0.5
      memory:
        guarantee: 512M
        limit: 1G

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: false
      userPlaceholder:
        enabled: false
