rbac:
  enabled: true

# letsencrypt:
#   contactEmail: hub23registry@turing.ac.uk

binderhub:
  config:
    BinderHub:
      use_registry: true
      auth_enabled: true

      template_path: /etc/binderhub/custom/templates
      extra_static_path: /etc/binderhub/custom/static
      extra_static_url_prefix: /extra_static/
      template_variables:
        EXTRA_STATIC_URL_PREFIX: "/extra_static/"

  # service:
  #   type: ClusterIP

  # ingress:
  #   enabled: true
  #   annotations:
  #     # cert-manager provides a TLS secret
  #     kubernetes.io/tls-acme: "true"
  #     # nginx-ingress controller to be explicitly utilised instead of "gce"
  #     kubernetes.io/ingress.class: nginx
  #   hosts:
  #     - binder.hub23.turing.ac.uk
  #   tls:
  #     - secretName: hub23-tls
  #       hosts:
  #         - binder.hub23.turing.ac.uk

  # networkPolicy:
  #   enabled: false
  #   egress:
  #     tcpPorts:
  #       - 80   # http
  #       - 443  # https
  #     cidr: 0.0.0.0/0

  jupyterhub:
    auth:
      admin:
        access: true
        users:
          - "sgibson91"

    # hub:
    #   networkPolicy:
    #     enabled: false

    # proxy:
    #   service:
    #     type: ClusterIP
    #   networkPolicy:
    #     enabled: false

    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/tls-acme: "true"
    #     kubernetes.io/ingress.class: nginx
    #   hosts:
    #     - hub.hub23.turing.ac.uk
    #   tls:
    #     - secretName: hub-hub23-tls
    #       hosts:
    #         - hub.hub23.turing.ac.uk

    # singleuser:
    #   networkPolicy:
    #     enabled: false
    #     egress: []

  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/alan-turing-institute/hub23-deploy
        - /etc/binderhub/custom
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/custom
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/custom

# nginx-ingress:
#   controller:
#     service:
#       loadBalancerIP: "52.233.189.185"
#     config:
#       proxy-body-size: 64m

# cert-manager:
#   ingressShim:
#     defaultIssuerName: "hub23"
#     defaultIssuerKind: "ClusterIssuer"
#     defaultACMEChallengeType: "http01"
