rbac:
  enabled: true

binderhub:
  config:
    BinderHub:
      use_registry: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    https:
      enabled: true
      type: kube-lego

  jupyterhub:
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/proxy-body-size: 64m
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
    proxy:
      nginx:
        resource:
          requests:
            memory: 256Mi
            cpu: "0.25"
          limits:
            memory: 1Gi
            cpu: 1

nginx-ingress:
  rbac:
    create: true

kube-lego:
  config:
    LEGO_EMAIL: hub23registry@turing.ac.uk
    LEGO_URL: https://acme-v01.api.letsencrypt.org.directory
  rbac:
    create: true
  image:
    tag: 0.1.7
