trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: LintAndValidateHelmChart
  steps:
  - task: HelmInstaller@1
    displayName: 'Stage 1 Step 1: Install helm'
    inputs:
      helmVersionToInstall: '3.3.4'

  - task: UsePythonVersion@0
    displayName: 'Stage 1 Step 2: Install Python 3.8'
    inputs:
      versionSpec: '3.8'
      addToPath: true

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Stage 1 Step 3: Install Python tools'

  - script: python -m pip install -r tests/requirements.txt
    displayName: 'Stage 1 Step 4: Install Python requirements'

  - task: Bash@3
    displayName: 'Stage 1 Step 5: Install kubeval'
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

  - task: Bash@3
    displayName: 'Stage 2 Step 1: Add helm chart repos'
    inputs:
      targetType: 'inline'
      script: |
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

  - task: Bash@3
    displayName: 'Stage 2 Step 2: Update local helm chart'
    inputs:
      targetType: 'inline'
      script: |
        cd hub23-chart && helm dep up && cd ..

  - task: PythonScript@0
    displayName: 'Stage 2 Step 3: Lint and validate hub23-chart'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'tests/lint-and-validate.py'
      arguments: '--values ../hub23-chart/values.yaml ../deploy/prod.yaml ../tests/test-values.yaml'
