trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Installation
  steps:
  - task: HelmInstaller@1
    displayName: 'Step 1: Install helm'
    inputs:
      helmVersionToInstall: '2.15.0'

  - task: UsePythonVersion@0
    displayName: 'Step 2: Install Python 3.7'
    inputs:
      versionSpec: '3.7'
      addToPath: true

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Step 3: Install Python tools'

  - script: python -m pip install -r tests/requirements.txt
    displayName: 'Step 4: Install Python requirements'

  - task: Bash@3
    displayName: 'Step 5: Install kubeval'
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

- job: LintAndValidateHelmChart
  dependsOn: Installation
  steps:

  - task: HelmDeploy@0
    displayName: 'Step 1: Initialise helm'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'hub23-deploy-scn'
      azureResourceGroup: 'Hub23'
      kubernetesCluster: 'hub23cluster'
      namespace: 'hub23'
      command: 'init'
      arguments: '--client-only'
      tillerNamespace: 'kube-system'

  - task: Bash@3
    displayName: 'Step 2: Add helm chart repos'
    inputs:
      targetType: 'inline'
      script: |
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
        helm repo add nginx-ingress https://kubernetes-charts.storage.googleapis.com
        helm repo add cert-manager https://charts.jetstack.io
        helm repo update

  - task: Bash@3
    displayName: 'Step 3: Update local helm chart'
    inputs:
      targetType: 'inline'
      script: |
        cd hub23-chart && helm dep up && cd ..

  - task: PythonScript@0
    displayName: 'Step 4: Lint and validate hub23-chart'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'tests/lint-and-validate.py'
      arguments: '--values ../hub23-chart/values.yaml ../deploy/prod.yaml ../tests/test-values.yaml'
