schedules:
- cron: "0 * * * *"
  displayName: Hourly subscription test
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CheckSubscriptionStatus
  steps:
  - task: CmdLine@2
    displayName: 'Install Azure CLI'
    inputs:
      script: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'

  - task: CmdLine@2
    inputs:
      script: |
        subStatus=$(az account show --subscription Turing-BinderHub --query state --output tsv)
        echo "The subscription is ${subStatus}"
        [[ $subStatus == 'Enabled' ]]
