schedules:
- cron: "0 * * * *"
  displayName: Hourly subscription test
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CheckSubscriptionStatus
  steps:
  - task: AzureCLI@2
    displayName: 'Get subscription status'
    name: getSubscriptionStatus
    inputs:
      azureSubscription: 'hub23-deploy-scn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'subStatus=$(az account show --subscription Turing-BinderHub --query state --output tsv)'

  - task: Bash@3
    displayName: 'Check subscription status'
    inputs:
      targetType: 'inline'
      script: |
        echo 'The subscription is $(subStatus)'
        [[ $subStatus == 'Enabled' ]]
