name: Automerge

on:
  pull_request:
    types:
      - labeled
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_ACTION_TOKEN }}"
          MERGE_LABELS: "automerge,!wip"
