name: Black

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint with black
        run: |
          black --check scripts/
          black --check tests/
