name: Build and Publish JupyterBook Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r docs/requirements.txt

      - name: Build JupyterBook
        working-directory: ./docs
        run: |
          jupyter-book build .

      - name: Check links with html proofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "./docs/_build/html"
          arguments: --assume-extension --disable-external --only_4xx
        continue-on-error: true

      - name: Publish book
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
