name: Validate Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          helmv3: 3.5.2
          command: |
            echo "#### Setup: Add helm charts"
            helmv3 repo add jupyterhub https://jupyterhub.github.io/helm-chart
            helmv3 repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helmv3 repo update
            echo "#### Setup: Update local chart"
            cd hub23-chart && helmv3 dep up && cd ..
            echo "#### TEST 1: Run helm lint"
            helmv3 lint hub23-chart \
              -f hub23-chart/values.yaml \
              -f deploy/prod.yaml \
              -f deploy/test-values.yaml \
              --debug
            echo "#### TEST 2: Run helm template and pipe to kubeval"
            helmv3 template hub23-chart \
              -f hub23-chart/values.yaml \
              -f deploy/prod.yaml \
              -f deploy/test-values.yaml \
              --debug | kubeval \
              --kubernetes-version 1.18.1 \
              --ignore-missing-schemas
